# See http://www.appveyor.com/docs/appveyor-yml for many more options

install:
  - cinst pester -y

build: false

test_script:
# Test with native PS version
  - ps: . .\Tests\appveyor.pester.ps1 -Test -Finalize